// PlataformaWEBAngular/src/app/modules/auth/login/login.component.ts
import { Component } from '@angular/core';
import { Router, RouterLink } from '@angular/router';
import { AuthService } from '../../../core/services/auth.service';
import { FormsModule } from '@angular/forms';
import { NgIf } from '@angular/common';

@Component({
  selector: 'app-login',
  standalone: true,
  imports: [FormsModule, RouterLink, NgIf],
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css'],
})
export class LoginComponent {
  email: string = '';
  password: string = '';
  error: string = '';

  constructor(private authService: AuthService, private router: Router) {}

  onLogin(): void {
    console.log('Enviando solicitud de login...');
    this.authService.login(this.email, this.password).subscribe({
      next: (response) => {
        this.authService.setToken(response.token); // Guarda el token
        console.log('Token recibido:', response.token);

        const role = this.authService.getUserRole(); // Obtén el rol del usuario
        console.log('Rol del usuario:', role);

        if (role === 'Administrador') {
          this.router.navigate(['/admin/dashboard']); // Redirige al dashboard de administrador
        } else if (role === 'Usuario') {
          this.router.navigate(['/home']); // Redirige al home para usuarios regulares
        } else {
          console.error('Rol desconocido:', role);
          this.error = 'Rol desconocido, no se puede redirigir.';
        }
      },
      error: (err) => {
        console.error('Error en el login:', err);
        this.error = 'Credenciales incorrectas';
      },
    });
  }


}

<div class="flex flex-col items-center justify-center min-h-screen bg-gray-100">
  <div class="w-full max-w-md p-6 bg-white rounded-lg shadow-md">
    <h1 class="text-2xl font-bold text-center text-blue-600 mb-4">Iniciar Sesión</h1>
    <form (submit)="onLogin()">
      <div class="mb-4">
        <label for="email" class="block text-gray-700 mb-2">Correo Electrónico</label>
        <input
          id="email"
          type="email"
          [(ngModel)]="email"
          name="email"
          class="w-full px-4 py-2 border rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-300"
          placeholder="Escribe tu correo"
          required
        />
      </div>
      <div class="mb-6">
        <label for="password" class="block text-gray-700 mb-2">Contraseña</label>
        <input
          id="password"
          type="password"
          [(ngModel)]="password"
          name="password"
          class="w-full px-4 py-2 border rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-300"
          placeholder="Escribe tu contraseña"
          required
        />
      </div>
      <button
        type="submit"
        class="w-full py-2 text-white bg-blue-500 rounded-lg hover:bg-blue-600 focus:outline-none focus:ring-2 focus:ring-blue-300"
      >
        Iniciar Sesión
      </button>
    </form>
    <p class="mt-4 text-center text-gray-600">
      ¿No tienes una cuenta?
      <a routerLink="/auth/register" class="text-blue-500 hover:underline">Regístrate aquí</a>
    </p>
    <p *ngIf="error" class="mt-4 text-sm text-center text-red-500">{{ error }}</p>
  </div>
</div>

// PlataformaWEB/src/components/Login.tsx
import { useState } from "react";
import api from "../api";

const Login = () => {
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [error, setError] = useState("");

  const handleLogin = async (e: React.FormEvent) => {
    e.preventDefault();
    try {
      const response = await api.post("/Auth/login", { email, password });
      localStorage.setItem("token", response.data.token);
      alert("Inicio de sesión exitoso");
      setError("");
    } catch (err) {
      console.error("Error en el inicio de sesión:", err);
      setError("Credenciales incorrectas. Inténtalo nuevamente.");
    }
  };

  return (
    <div className="min-h-screen flex items-center justify-center bg-gradient-to-br from-blue-100 to-blue-200">
      <div className="bg-white shadow-lg rounded-lg p-8 w-full max-w-md">
        <h2 className="text-2xl font-bold text-center text-blue-600 mb-4">Iniciar Sesión</h2>
        {error && <p className="text-red-500 text-sm text-center mb-4">{error}</p>}
        <form onSubmit={handleLogin}>
          <div className="mb-4">
            <label className="block text-gray-700 mb-2">Correo Electrónico</label>
            <input
              type="email"
              value={email}
              onChange={(e) => setEmail(e.target.value)}
              className="w-full border rounded-lg px-4 py-2 focus:outline-none focus:ring focus:ring-blue-300"
              placeholder="Escribe tu correo"
              required
            />
          </div>
          <div className="mb-6">
            <label className="block text-gray-700 mb-2">Contraseña</label>
            <input
              type="password"
              value={password}
              onChange={(e) => setPassword(e.target.value)}
              className="w-full border rounded-lg px-4 py-2 focus:outline-none focus:ring focus:ring-blue-300"
              placeholder="Escribe tu contraseña"
              required
            />
          </div>
          <button
            type="submit"
            className="w-full bg-blue-500 text-white py-2 rounded-lg hover:bg-blue-600 transition duration-300"
          >
            Iniciar Sesión
          </button>
        </form>
        <p className="text-center text-gray-600 mt-4">
          ¿No tienes una cuenta?{" "}
          <a href="/register" className="text-blue-500 hover:underline">
            Regístrate aquí
          </a>
        </p>
      </div>
    </div>
  );
};

export default Login;
