// PlataformaWEBAngular/src/app/modules/user/pages/home/home.component.ts
import { Component } from '@angular/core';
import { Router } from '@angular/router';
import { AuthService } from '../../../../core/services/auth.service';


@Component({
  selector: 'app-home',
  standalone: true,
  imports: [],
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.css'],
})
export class HomeComponent {
  userRole: string | null = '';
  userName: string | null = '';

  constructor(private authService: AuthService, private router: Router) {}

  ngOnInit(): void {
    this.userRole = this.authService.getUserRole();
    this.userName = this.authService.getToken() ? 'Usuario Logeado' : null; // Cambia según tu lógica de backend
  }

  logout(): void {
    this.authService.logout();
    this.router.navigate(['/login']);
  }
}

<div class="min-h-screen flex items-center justify-center bg-gradient-to-br from-green-100 to-green-300">
  <div class="bg-white shadow-md rounded-lg p-8 max-w-md w-full text-center">
    <h1 class="text-2xl font-bold text-green-700">Bienvenido</h1>
    <p class="text-gray-700 mt-2">
      Hola, <span class="font-semibold">{{ userName }}</span>!
    </p>
    <p class="text-sm text-gray-500 mt-1">
      Rol actual: <span class="font-semibold">{{ userRole }}</span>
    </p>
    <button
      class="mt-6 bg-red-500 text-white py-2 px-4 rounded-lg hover:bg-red-600 transition duration-300"
      (click)="logout()"
    >
      Cerrar Sesión
    </button>
  </div>
</div>

// PlataformaWEB/src/components/Home/Home.tsx
import { useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";
import { jwtDecode } from "jwt-decode";

interface DecodedToken {
  nombre: string;
  rol: string;
  email: string;
}

const Home = () => {
  const [userName, setUserName] = useState<string | null>(null);
  const navigate = useNavigate();

  useEffect(() => {
    const token = localStorage.getItem("token");

    if (!token) {
      navigate("/login"); // Redirige al login si no hay token
    } else {
      try {
        const decodedToken: DecodedToken = jwtDecode<DecodedToken>(token);
        setUserName(decodedToken.nombre || "Usuario");
      } catch (error) {
        console.error("Error al decodificar el token:", error);
        navigate("/login");
      }
    }
  }, [navigate]);

  const handleLogout = () => {
    localStorage.removeItem("token");
    navigate("/login");
  };

  return (
    <div className="min-h-screen flex flex-col items-center justify-center bg-gradient-to-br from-gray-100 to-gray-200">
      <div className="bg-white shadow-lg rounded-lg p-8 w-full max-w-lg text-center">
        <h1 className="text-3xl font-bold text-gray-800 mb-4">
          Bienvenido, {userName}!
        </h1>
        <p className="text-gray-600 mb-6">
          Has iniciado sesión correctamente. Disfruta de la plataforma.
        </p>
        <button
          onClick={handleLogout}
          className="bg-red-500 text-white px-6 py-2 rounded-lg font-semibold hover:bg-red-600 transition duration-300"
        >
          Cerrar Sesión
        </button>
      </div>
    </div>
  );
};

export default Home;
