// PlataformaWEB/src/components/Auth/Register.tsx
import { useState } from "react";
import { useNavigate } from "react-router-dom";
import api from "../../api";

const Register = () => {
  const [nombre, setNombre] = useState("");
  const [apellido, setApellido] = useState("");
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [error, setError] = useState("");
  const [success, setSuccess] = useState("");
  const navigate = useNavigate();

  const handleRegister = async (e: React.FormEvent) => {
    e.preventDefault();
    try {
      const response = await api.post("/Auth/registro", {
        nombre,
        apellido,
        email,
        password,
      });

      // Guarda el token en localStorage si la API lo devuelve
      localStorage.setItem("token", response.data.token);

      // Mostrar éxito y redirigir al Home
      setSuccess("Registro exitoso. Redirigiendo...");
      setError("");

      // Redirigir al Home después de un breve retraso
      setTimeout(() => {
        navigate("/home");
      }, 1000);
    } catch (err) {
      console.error("Error en el registro:", err);
      setError("Ocurrió un error al registrarte. Inténtalo nuevamente.");
      setSuccess("");
    }
  };

  return (
    <div className="min-h-screen flex items-center justify-center bg-gradient-to-br from-green-100 to-green-200">
      <div className="bg-white shadow-lg rounded-lg p-8 w-full max-w-md">
        <h2 className="text-2xl font-bold text-center text-green-600 mb-4">
          Registro
        </h2>
        {error && (
          <p className="text-red-500 text-sm text-center mb-4">{error}</p>
        )}
        {success && (
          <p className="text-green-500 text-sm text-center mb-4">{success}</p>
        )}
        <form onSubmit={handleRegister}>
          <div className="mb-4">
            <label className="block text-gray-700 mb-2">Nombre</label>
            <input
              type="text"
              value={nombre}
              onChange={(e) => setNombre(e.target.value)}
              className="w-full border rounded-lg px-4 py-2 focus:outline-none focus:ring focus:ring-green-300"
              placeholder="Escribe tu nombre"
              required
            />
          </div>
          <div className="mb-4">
            <label className="block text-gray-700 mb-2">Apellido</label>
            <input
              type="text"
              value={apellido}
              onChange={(e) => setApellido(e.target.value)}
              className="w-full border rounded-lg px-4 py-2 focus:outline-none focus:ring focus:ring-green-300"
              placeholder="Escribe tu apellido"
              required
            />
          </div>
          <div className="mb-4">
            <label className="block text-gray-700 mb-2">Correo Electrónico</label>
            <input
              type="email"
              value={email}
              onChange={(e) => setEmail(e.target.value)}
              className="w-full border rounded-lg px-4 py-2 focus:outline-none focus:ring focus:ring-green-300"
              placeholder="Escribe tu correo"
              required
            />
          </div>
          <div className="mb-6">
            <label className="block text-gray-700 mb-2">Contraseña</label>
            <input
              type="password"
              value={password}
              onChange={(e) => setPassword(e.target.value)}
              className="w-full border rounded-lg px-4 py-2 focus:outline-none focus:ring focus:ring-green-300"
              placeholder="Escribe tu contraseña"
              required
            />
          </div>
          <button
            type="submit"
            className="w-full bg-green-500 text-white py-2 rounded-lg hover:bg-green-600 transition duration-300"
          >
            Registrarse
          </button>
        </form>
        <p className="text-center text-gray-600 mt-4">
          ¿Ya tienes una cuenta?{" "}
          <a href="/login" className="text-green-500 hover:underline">
            Inicia sesión
          </a>
        </p>
      </div>
    </div>
  );
};

export default Register;

// PlataformaWEBAngular/src/app/modules/auth/register/register.component.ts
import { Component } from '@angular/core';
import { Router, RouterLink } from '@angular/router';
import { AuthService } from '../../../core/services/auth.service';
import { FormsModule } from '@angular/forms';
import { NgIf } from '@angular/common';

@Component({
  selector: 'app-register',
  standalone: true,
  imports: [FormsModule, NgIf, RouterLink],
  templateUrl: './register.component.html',
  styleUrls: ['./register.component.css'],
})
export class RegisterComponent {
  nombre: string = '';
  apellido: string = '';
  email: string = '';
  password: string = '';
  error: string = '';

  constructor(private authService: AuthService, private router: Router) {}

  onRegister(): void {
    this.authService
      .register(this.nombre, this.apellido, this.email, this.password)
      .subscribe({
        next: (response) => {
          console.log(response.mensaje); // Muestra el mensaje de éxito
          this.router.navigate(['/auth/login']); // Redirigir al login después del registro
        },
        error: (err) => {
          this.error = err.error.mensaje || 'Error al registrarse';
          console.error(err);
        },
      });
  }

}

<div class="min-h-screen flex items-center justify-center bg-gradient-to-br from-blue-100 to-blue-200">
  <div class="bg-white shadow-lg rounded-lg p-8 w-full max-w-md">
    <h2 class="text-2xl font-bold text-center text-blue-600 mb-4">Registro</h2>
    <form (ngSubmit)="onRegister()">
      <div class="mb-4">
        <label for="nombre" class="block text-gray-700 mb-2">Nombre</label>
        <input
          id="nombre"
          type="text"
          [(ngModel)]="nombre"
          name="nombre"
          class="w-full border rounded-lg px-4 py-2 focus:outline-none focus:ring focus:ring-blue-300"
          placeholder="Escribe tu nombre"
          required
        />
      </div>
      <div class="mb-4">
        <label for="apellido" class="block text-gray-700 mb-2">Apellido</label>
        <input
          id="apellido"
          type="text"
          [(ngModel)]="apellido"
          name="apellido"
          class="w-full border rounded-lg px-4 py-2 focus:outline-none focus:ring focus:ring-blue-300"
          placeholder="Escribe tu apellido"
          required
        />
      </div>
      <div class="mb-4">
        <label for="email" class="block text-gray-700 mb-2">Correo Electrónico</label>
        <input
          id="email"
          type="email"
          [(ngModel)]="email"
          name="email"
          class="w-full border rounded-lg px-4 py-2 focus:outline-none focus:ring focus:ring-blue-300"
          placeholder="Escribe tu correo"
          required
        />
      </div>
      <div class="mb-6">
        <label for="password" class="block text-gray-700 mb-2">Contraseña</label>
        <input
          id="password"
          type="password"
          [(ngModel)]="password"
          name="password"
          class="w-full border rounded-lg px-4 py-2 focus:outline-none focus:ring focus:ring-blue-300"
          placeholder="Escribe tu contraseña"
          required
        />
      </div>
      <button
        type="submit"
        class="w-full bg-blue-500 text-white py-2 rounded-lg hover:bg-blue-600 transition duration-300"
      >
        Registrarse
      </button>
    </form>
    <p class="text-center text-gray-600 mt-4">
      ¿Ya tienes una cuenta?
      <a
        routerLink="/auth/login"
        class="text-blue-500 hover:underline"
      >
        Inicia sesión aquí
      </a>
    </p>
    <p *ngIf="error" class="text-red-500 text-sm mt-4">{{ error }}</p>
  </div>
</div>
